config/routes.rb
Rails.application.routes.draw do
  resources :personnels

  get "password_resets/new"
  get 'current_user' => "personnels#current_user"
  get "sessions/new"

  get "log_out" => 'sessions#destroy', :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'sessions#new'
  resources :sessions
  resources :password_resets

  # resources :personnels do
  #   collection do
  #     match 'search' => 'personnels#search', via: [:get, :post], as: :search
  #   end
  # end

  # resources :labels, only: :index do
  #   match 'search' => 'labels#search',
  #         on: :collection, via: [:get, :post], as: :advanced_search
  # end

  get "windows/index"

  get "windows/upload_image"
  post "windows/upload_image"

  get "windows/image_upload"
  post "windows/image_upload"

  get "windows/upload_register"
  post "windows/upload_register"

  get "windows/uploads"
  post "windows/uploads"

  get "windows/process_image"
  post "windows/process_image"

  get "windows/processed_images"
  post "windows/processed_images"

  get "windows/unprocessed_uploads"
  post "windows/unprocessed_uploads"

  get "windows/search_index"
  post "windows/search_index"

  get "windows/search"
  post "windows/search"

  get "windows/autocomplete_web_entities"
  post "windows/autocomplete_web_entities"
  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  	end
  	def create
  user = Personnel.find_by_email(params[:email])
  user.send_password_reset if user
  redirect_to root_url, :notice => "Email sent with password reset instructions."
end
  
  def edit
  @user = Personnel.find_by_password_reset_token!(params[:id])
end

def update
  @user = Personnel.find_by_password_reset_token!(params[:id])
  if @user.password_reset_sent_at < 2.hours.ago
    redirect_to new_password_reset_path, :alert => "Password &crarr; 
      reset has expired."
  elsif @user.update_attributes(params[:personnel].permit(:password, :password_confirmation))
  	@user.update(password_reset_token: nil, password_reset_sent_at: nil)
    redirect_to root_url, :notice => "Password has been reset."
  else
    render :edit
  end
end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Update Password" %></div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="actions"><%= submit_tag "Reset Password" %></div>
<% end %>