config/routes.rb
Rails.application.routes.draw do
  resources :personnels

  get "password_resets/new"
  get 'current_user' => "personnels#current_user"
  get "sessions/new"

  get "log_out" => 'sessions#destroy', :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'sessions#new'
  resources :sessions
  resources :password_resets

  # resources :personnels do
  #   collection do
  #     match 'search' => 'personnels#search', via: [:get, :post], as: :search
  #   end
  # end

  # resources :labels, only: :index do
  #   match 'search' => 'labels#search',
  #         on: :collection, via: [:get, :post], as: :advanced_search
  # end

  get "windows/index"

  get "windows/upload_image"
  post "windows/upload_image"

  get "windows/image_upload"
  post "windows/image_upload"

  get "windows/upload_register"
  post "windows/upload_register"

  get "windows/uploads"
  post "windows/uploads"

  get "windows/process_image"
  post "windows/process_image"

  get "windows/processed_images"
  post "windows/processed_images"

  get "windows/unprocessed_uploads"
  post "windows/unprocessed_uploads"

  get "windows/search_index"
  post "windows/search_index"

  get "windows/search"
  post "windows/search"

  get "windows/autocomplete_web_entities"
  post "windows/autocomplete_web_entities"
  
end

app/controllers/windows_controller.rb
class WindowsController < ApplicationController
	before_filter :search_index
	require 'bigdecimal'
	require 'active_support'
	
	def index
	end

	def upload_image
	end

	def image_upload
		@personnel=current_personnel
		if params[:images]
	        params[:images].each { |image|
	        @personnel.images.create(scan: image)
	        }
	    end
		redirect_to :back
	end

	def search_index
		if params[:label_description]
			label_description = params[:label_description]
			@labels=Label.where(:description => label_description)
			@web_entities=WebEntity.where(:description => label_description)
			@combined_web_elements = []
			@labels.each do |label|
				@combined_web_elements += [[label.image, label.description, label.score]]
			end
 			@web_entities.each do |web_entity|
				@combined_web_elements += [[web_entity.image, web_entity.description, web_entity.score]]				
			end
			@combined_web_elements=@combined_web_elements.sort_by{|elem| elem[2]}.reverse!
		else
		end
	end

	def uploads
		if params[:term] != nil
			label_description = params[:term]
			@labels=Label.where(:description => label_description)
			@web_entities=WebEntity.where(:description => label_description)
			@combined_web_elements = []
			@labels.each do |label|
				@combined_web_elements += [[label.image, label.description, label.score]]
			end
 			@web_entities.each do |web_entity|
				@combined_web_elements += [[web_entity.image, web_entity.description, web_entity.score]]				
			end
			@combined_web_elements=@combined_web_elements.sort_by{|elem| elem[2]}.reverse!
		else
			@combined_web_elements = []
			web_entities=WebEntity.select(:description, :score).group(:description, :score).having("count(*) > 2").size
			web_entities.each do |elem|
				weight = (elem[0][1]*elem[1]).to_f
				@combined_web_elements += [[elem[0][0], weight]]
			end
			labels=Label.select(:description, :score).group(:description, :score).having("count(*) > 2").size
			labels.each do |elem|
				weight = (elem[0][1]*elem[1]).to_f
				@combined_web_elements += [[elem[0][0], weight]]
			end
			@combined_web_elements = @combined_web_elements.sort_by{|elem| elem[0]}.reverse!
			# @web_weight_elements = []
			# @combined_web_elements.each do |element|
			# 	@web_weight_elements += [element[0]]
			# end 
			@keywords = []
			@combined_web_elements.each do |elem|
				if elem[0] == '' || elem[0] == nil
	 			else
	 				@keywords += [elem[0]]
	 			end
			end
			@keywords = @keywords.uniq
		end
	end


	def upload_register
		if params.select{|key, value| value == ">" }.keys[0] != nil
			redirect_to :controller => 'windows', :action => 'processed_images', :image_id => params.select{|key, value| value == ">" }.keys[0]
		else
			@images = Image.all
		end
	end

	def processed_images
		link=params[:image_id]
		@picked_image = Image.find(link)
	end

	def unprocessed_uploads
		@images = Image.where(processed: nil)
	end

	def process_image
		link=params[:image_id]
		picked_image = Image.find(link)
		
		require "google/cloud/vision"
		Google::Cloud::Vision.configure do |config|
		  config.project_id  = "lottery-220502"
		  config.credentials = File.join(Rails.root, 'lottery-c12cc4ecd43a.json')
		end

		vision = Google::Cloud::Vision.new
		image = vision.image "https:"+picked_image.scan.url
		document = image.document
		@text=document.text

		@label=image.labels
		@label.each do |label|
			label_instance = Label.new
			label_instance.description = label.description
			label_instance.score = label.score
			label_instance.image_id = link.to_i
			label_instance.identification_code = label.mid
			label_instance.save
		end
		
		web = image.web
		@web_entities=web.entities
		@web_entities.each do |web_entity|
			web_entity_instance = WebEntity.new
			web_entity_instance.description = web_entity.description
			web_entity_instance.score = web_entity.score
			web_entity_instance.image_id = link.to_i
			web_entity_instance.identification_code = web_entity.entity_id
			web_entity_instance.save
		end
	end

	def autocomplete_web_entities
	  label_description = params[:term]
	  label_description=label_description.gsub(/\(/, '')
	  label_description=label_description.gsub(/\)/, '')
	  label_description=label_description.gsub(/\&/, '')  
	  label_description=label_description.gsub(/\s+$/, '')
	  label_description=label_description.gsub(/\:/, '')
	  label_description=(label_description.gsub(/\s+/, '&'))+":*"
	  labels = WebEntity.all.where("to_tsvector(description) @@ to_tsquery(:q)", q: label_description)
	  render :json => labels.map { |label| {:id => label.id, :label => label.description , :value => label.description } }
	end
end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/windows/process_image.html.erb
<table class="table table-striped table-hover table-primary">
  <thead>
  	<tr>
  		<th></th>
  	</tr>
  </thead>
  <tbody>
  	<tr>
  		<td><%= @label %></td>
  	</tr>
  </tbody>
</table>

<table class="table table-striped table-hover table-primary">
  <thead>
  	<tr>
  		<th></th>
  	</tr>
  </thead>
  <tbody>
  	<tr>
  		<td><%= @web_entities %></td>
  	</tr>
  </tbody>
</table>

app/views/windows/processed_images.html.erb
<%= form_tag 'processed_images', :authenticity_token => true, :html => {:class => 'form-horizontal'}  do %>
<center>
  <iframe src= "<%= @picked_image.scan.url %>" class="well" height="1100" width="900" frameborder="1" onload= "resizeIframe(this)" ></iframe>
</center>


<table class="table table-striped table-hover table-primary" id="label_list">
  <thead>
  	<tr>
  		<th>Google Vision Label Id</th>
  		<th>Description</th>
  		<th>Score</th>
  		<th>Upload Date</th>
  		<th>Image Name</th>
  		<th>By</th>
  	</tr>
  </thead>
  <tbody>
    <% @picked_image.labels.each do |label| %>
    	<tr>
    		<td><%= label.identification_code %></td>
    		<td><%= label.description %></td>
    		<td><%= label.score %></td>
        <td><%= @picked_image.scan_file_name %></td>
    		<td><%= @picked_image.created_at.strftime("%d/%m/%y") %></td>
    		<td><%= @picked_image.personnel.name %></td>
    	</tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<br>
<table class="table table-striped table-hover table-primary" id="web_entities_list" >
  <thead>
    <tr>
      <th>Google Vision Label Id</th>
      <th>Description</th>
      <th>Score</th>
      <th>Upload Date</th>
      <th>Image Name</th>
      <th>By</th>
    </tr>
  </thead>
  <tbody>
    <% @picked_image.web_entities.each do |web_entity| %>
      <tr>
        <td><%= web_entity.identification_code %></td>
        <td><%= web_entity.description %></td>
        <td><%= web_entity.score %></td>
        <td><%= @picked_image.scan_file_name %></td>
        <td><%= @picked_image.created_at.strftime("%d/%m/%y") %></td>
        <td><%= @picked_image.personnel.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>
<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

app/views/windows/search_index.html.erb
<%= form_tag 'search_index', :authenticity_token => true, :html => {:class => 'form-horizontal'} do %><section class="home-banner-area relative">
	<div class="container">
		<div class="row fullscreen d-flex align-items-center justify-content-center">
			<div class="banner-content col-lg-8 col-md-12">
			<h1 class="wow fadeIn" data-wow-duration="4s"><br> </h1>
							<p class="text-white">
							</p>
			<div class="input-wrap">
				<form action="" class="form-box d-flex justify-content-between">
					<div class="col-md-12 col-lg-12">
					<div class="col-md-10 col-lg-10">
					<%= autocomplete_field_tag 'label_description', '', windows_autocomplete_web_entities_path, class: 'form-control' %></div>
					<div class="col-md-2 col-lg-2">
					<button type="submit" class="btn search-btn btn-success">Search</button></div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
</section>
<%= hidden_field_tag :label_description, nil %>
<br>
<br>
<% if @combined_web_elements != nil %>
	<% @combined_web_elements.each do |element| %>	
		<section class="faculty-area section-gap">
			<div class="thumb d-flex justify-content-center">
				<img class="img-fluid" src="<%= element[0].scan.url %>" alt="">
			</div>
			<div class="meta-text text-center">
				<h4><%= link_to element[0].scan_file_name, element[0].scan.url, target: :_blank %></h4>
			</div>
		</section>
	<% end %>
<% end %>
<% end %>

app/views/windows/unprocessed_uploads.html.erb
<table class="table table-striped table-hover table-primary">
  <thead>
   <tr>
      <th></th>
      <th>Id</th>
      <th>FileName</th>
      <th>Upload Date</th>
      <th>By</th>
      <th></th>
   </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
    <tr>
      <td></td>
      <td><%= image.id %></td>
      <td><%= link_to image.scan_file_name, image.scan.url, target: :_blank %></td>
      <td><%= image.created_at.strftime("%d/%m/%y") %></td>
      <td><%= image.personnel.name %></td>
      <td><%= submit_tag ">", name: image.id, :class => 'btn btn-default btn-xs arrowhead'%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/windows/upload_image.html.erb
<div class="col-lg-4 col-lg-offset-4">
  <div class="well bs-component">
  <legend>&nbsp&nbsp&nbsp&nbsp&nbsp&nbspUpload Image</legend> 
  <br>
  <br>
  <%= form_tag 'image_upload', multipart: true  do %>
    <div class="col-lg-8">
      <%= file_field_tag "images[]",type: :file, multiple: true, class: 'filestyle', :'data-classButton' => 'btn btn-primary' %>
    </div>
    <br>
    <br>
    <center>
    <%= button_tag type: 'submit', name:'submit', :class =>"btn btn-success"  ,'data-toogle' => "tooltip",'title' => "Upload Image"  do %>
      <%= content_tag :strong, 'Upload' %></center>
    <% end %>
  <% end %>
  </div>
</div>

app/views/windows/upload_register.html.erb
<%= form_tag 'upload_register', :authenticity_token => true, :html => {:class => 'form-horizontal'}  do %>
<table class="table table-striped table-hover table-primary">
  <thead>
   <tr>
      <th></th>
      <th>Id</th>
      <th>FileName</th>
      <th>Upload Date</th>
      <th>By</th>
      <th></th>
   </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
    <tr>
      <td></td>
      <td><%= image.id %></td>
      <td><%= link_to image.scan_file_name, image.scan.url, target: :_blank %></td>
      <td><%= image.created_at.strftime("%d/%m/%y") %></td>
      <td><%= image.personnel.name %></td>
      <td><%= submit_tag ">", name: image.id, :class => 'btn btn-default btn-xs arrowhead'%></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/windows/uploads.html.erb
<%= form_tag 'uploads', :authenticity_token => true, :html => {:class => 'form-horizontal'}  do %>
	<%  if @keywords == nil %>
		<% @combined_web_elements.each do |element| %>	
			<section class="faculty-area section-gap">
				<div class="thumb d-flex justify-content-center">
					<img class="img-fluid" src="<%= element[0].scan.url %>" alt="">
				</div>
				<div class="meta-text text-center">
					<h4><%= link_to element[0].scan_file_name, element[0].scan.url, target: :_blank %></h4>
				</div>
			</section>
		<% end %>
	<% else %>	
		<center>
			<% @keywords.each do |elem| %>
				<%= submit_tag elem, name: "term", :class => "btn btn-outline-success" %>
			<% end %>
		</center>
	<% end %>
<% end %>