config/routes.rb
Rails.application.routes.draw do
  resources :personnels

  get "password_resets/new"
  get 'current_user' => "personnels#current_user"
  get "sessions/new"

  get "log_out" => 'sessions#destroy', :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'sessions#new'
  resources :sessions
  resources :password_resets

  # resources :personnels do
  #   collection do
  #     match 'search' => 'personnels#search', via: [:get, :post], as: :search
  #   end
  # end

  # resources :labels, only: :index do
  #   match 'search' => 'labels#search',
  #         on: :collection, via: [:get, :post], as: :advanced_search
  # end

  get "windows/index"

  get "windows/upload_image"
  post "windows/upload_image"

  get "windows/image_upload"
  post "windows/image_upload"

  get "windows/upload_register"
  post "windows/upload_register"

  get "windows/uploads"
  post "windows/uploads"

  get "windows/process_image"
  post "windows/process_image"

  get "windows/processed_images"
  post "windows/processed_images"

  get "windows/unprocessed_uploads"
  post "windows/unprocessed_uploads"

  get "windows/search_index"
  post "windows/search_index"

  get "windows/search"
  post "windows/search"

  get "windows/autocomplete_web_entities"
  post "windows/autocomplete_web_entities"
  
end

app/models/personnel.rb
class Personnel < ActiveRecord::Base

  attr_accessor :password
  before_save :encrypt_password, :except => :send_password_reset 
  before_update :encrypt_password, :except => :send_password_reset 
  
  validates :password, :format => {:with => /(?=.*[a-zA-Z])(?=.*[0-9]).{6,}/, message: "must be at least 6 characters and include one number and one letter"}
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create 
  validates_presence_of :email

  validates_uniqueness_of :email
  validates_uniqueness_of :name
  before_create { generate_token(:auth_token) }
  has_many :images
	
def send_password_reset
  generate_token(:password_reset_token)
   self.password_reset_sent_at = Time.zone.now
  save!(:validate => false)
  UserMailer.password_reset(self).deliver
end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Personnel.exists?(column => self[column])
  end
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user
    else
      user = find_by_name(email)
    end
    if user && user.passwordhash == BCrypt::Engine.hash_secret(password, user.passwordsalt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.passwordsalt = BCrypt::Engine.generate_salt
      self.passwordhash = BCrypt::Engine.hash_secret(password, passwordsalt)
    end
  end
  
end

app/controllers/personnels_controller.rb
class PersonnelsController < ApplicationController
  before_action :set_personnel, only: [:show, :edit, :update, :destroy]

  # GET /personnels
  # GET /personnels.json
  def index
    @personnels = Personnel.all
  end

  # GET /personnels/1
  # GET /personnels/1.json
  def show
  end

  # GET /personnels/new
  def new
    @personnel = Personnel.new
  end

  # GET /personnels/1/edit
  def edit
  end

  # POST /personnels
  # POST /personnels.json
  def create
    @personnel = Personnel.new(personnel_params)

    respond_to do |format|
      if @personnel.save
        format.html { redirect_to log_in_url, :notice => "Signed up!"  }
        format.json { render action: 'show', status: :created, location: @personnel }
      else
        format.html { render action: 'new' }
        format.json { render json: @personnel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnels/1
  # PATCH/PUT /personnels/1.json
  def update
    respond_to do |format|
      if @personnel.update(personnel_params)
        format.html { redirect_to @personnel, notice: 'Personnel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @personnel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnels/1
  # DELETE /personnels/1.json
  def destroy
    @personnel.destroy
    respond_to do |format|
      format.html { redirect_to personnels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personnel
      @personnel = Personnel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personnel_params
      params.require(:personnel).permit(:email, :name, :passwordhash, :passwordsalt, :auth_token, :password_reset_token, :password_reset_sent_at, :mobile, :password_confirmation, :password)
    end
end

app/helpers/personnels_helper.rb
module PersonnelsHelper
end

app/views/personnels/_form.html.erb
<%= form_for(@personnel) do |f| %>
  <% if @personnel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personnel.errors.count, "error") %> prohibited this personnel from being saved:</h2>

      <ul>
      <% @personnel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :passwordhash %><br>
    <%= f.text_field :passwordhash %>
  </div>
  <div class="field">
    <%= f.label :passwordsalt %><br>
    <%= f.text_field :passwordsalt %>
  </div>
  <div class="field">
    <%= f.label :auth_token %><br>
    <%= f.text_field :auth_token %>
  </div>
  <div class="field">
    <%= f.label :password_reset_token %><br>
    <%= f.text_field :password_reset_token %>
  </div>
  <div class="field">
    <%= f.label :password_reset_sent_at %><br>
    <%= f.datetime_select :password_reset_sent_at %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personnels/edit.html.erb
<h1>Editing personnel</h1>

<%= render 'form' %>

<%= link_to 'Show', @personnel %> |
<%= link_to 'Back', personnels_path %>

app/views/personnels/index.html.erb
<h1>Listing personnels</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Passwordhash</th>
      <th>Passwordsalt</th>
      <th>Auth token</th>
      <th>Password reset token</th>
      <th>Password reset sent at</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnels.each do |personnel| %>
      <tr>
        <td><%= personnel.email %></td>
        <td><%= personnel.name %></td>
        <td><%= personnel.passwordhash %></td>
        <td><%= personnel.passwordsalt %></td>
        <td><%= personnel.auth_token %></td>
        <td><%= personnel.password_reset_token %></td>
        <td><%= personnel.password_reset_sent_at %></td>
        <td><%= personnel.mobile %></td>
        <td><%= link_to 'Show', personnel %></td>
        <td><%= link_to 'Edit', edit_personnel_path(personnel) %></td>
        <td><%= link_to 'Destroy', personnel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personnel', new_personnel_path %>

app/views/personnels/new.html.erb
<%= form_for @personnel, :html => {:class => 'form-horizontal'} do |f| %>

<% if @personnel.errors.any? %>
  
  <div class="alert alert-dismissable alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <ul>
  <% for message in @personnel.errors.full_messages %>
  <li><%= message %><u><a href="#leg" class="alert-link">    Plz Submit again</a></u></li>
  <% end %>
  </ul>
</div>
  
  <% end %>
  

<fieldset>
    <div class="col-lg-4 col-lg-offset-4">
 <legend><a id="leg"><span class="glyphicon glyphicon-edit"></span>  Searchdoc</a></legend>
 </div>
 <br><br><br>
  
  <div class="form-group">
    <%= f.label :name, :class => "col-lg-4 control-label"  %>
  <div class="col-lg-4">
    <%= f.text_field :name, :class => "form-control", :placeholder => "Name", :id => "Name"  %>
  </div>
    </div>
  
     
   
   <div class="form-group">
    <%= f.label :email, :class => "col-lg-4 control-label"  %>
   <div class="col-lg-4">
    <%= f.text_field :email, :class => "form-control", :placeholder => "Email", :id => "inputEmail"  %>
  </div>
    </div>
  
  <div class="form-group">
    <%= f.label :mobile, :class => "col-lg-4 control-label"  %>
   <div class="col-lg-4">
    <%= f.text_field :mobile, :class => "form-control", :placeholder => "Mobile", :id => "inputMobile"  %>
  </div>
    </div>
  
  
 <div class="form-group">
    <%= f.label :password, :class => "col-lg-4 control-label"   %>
  <div class="col-lg-4">
    <%= f.password_field :password, :class => "form-control", :placeholder => "Password", :id => "inputPassword"   %>
 </div>
    </div>
  
  
  
  
   <div class="form-group">
    <%= f.label :password_confirmation, :class => "col-lg-4 control-label"  %>
  <div class="col-lg-4">
    <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "Password Confirmation", :id => "confirmPassword"  %>
   </div>
    </div>
  
  
  
   
 

 
  

  <div class="form-group">
      <div class="col-lg-4 col-lg-offset-4">
    
    <%= f.submit 'Sign up', :class => 'btn btn-primary' %> 
    </div>
    </div>
</fieldset>
<% end %>
 
  

app/views/personnels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @personnel.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @personnel.name %>
</p>

<p>
  <strong>Passwordhash:</strong>
  <%= @personnel.passwordhash %>
</p>

<p>
  <strong>Passwordsalt:</strong>
  <%= @personnel.passwordsalt %>
</p>

<p>
  <strong>Auth token:</strong>
  <%= @personnel.auth_token %>
</p>

<p>
  <strong>Password reset token:</strong>
  <%= @personnel.password_reset_token %>
</p>

<p>
  <strong>Password reset sent at:</strong>
  <%= @personnel.password_reset_sent_at %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @personnel.mobile %>
</p>

<%= link_to 'Edit', edit_personnel_path(@personnel) %> |
<%= link_to 'Back', personnels_path %>