config/routes.rb
Rails.application.routes.draw do
  resources :personnels

  get "password_resets/new"
  get 'current_user' => "personnels#current_user"
  get "sessions/new"

  get "log_out" => 'sessions#destroy', :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'sessions#new'
  resources :sessions
  resources :password_resets

  # resources :personnels do
  #   collection do
  #     match 'search' => 'personnels#search', via: [:get, :post], as: :search
  #   end
  # end

  # resources :labels, only: :index do
  #   match 'search' => 'labels#search',
  #         on: :collection, via: [:get, :post], as: :advanced_search
  # end

  get "windows/index"

  get "windows/upload_image"
  post "windows/upload_image"

  get "windows/image_upload"
  post "windows/image_upload"

  get "windows/upload_register"
  post "windows/upload_register"

  get "windows/uploads"
  post "windows/uploads"

  get "windows/process_image"
  post "windows/process_image"

  get "windows/processed_images"
  post "windows/processed_images"

  get "windows/unprocessed_uploads"
  post "windows/unprocessed_uploads"

  get "windows/search_index"
  post "windows/search_index"

  get "windows/search"
  post "windows/search"

  get "windows/autocomplete_web_entities"
  post "windows/autocomplete_web_entities"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">  
<% if @header==nil %>
<% @header='SearchImg' %>
<% end %>
  <title><%= @header %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "autocomplete-rails.js", "highcharts" %>
  <%= csrf_meta_tags %>
 <style><%= yield :stylesheets %></style>
</head>
<body>

<div id="user_nav">  
  <% if current_personnel %>
  	
	
	<div class = "navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"><%= current_personnel.name %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <h5><%= link_to 'Onboard', {controller: 'windows', action: 'index'}, { :class=>"nav-link"} %></h5>
      </li>
      <li class="nav-item">
      <li class="nav-item active">
        <h5><%= link_to 'Home', {controller: 'windows', action: 'index'}, { :class=>"nav-link"} %></h5>
      </li>
      <li class="nav-item">
    </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item">
          <%= link_to "LogOut", log_out_path, { :class=>"nav-link" } %>
        </li>
      </ul>
  </div>

  
  <% else %>
  <%=notice %>
 
  
  <%end %>

</div>

<div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>
</body>
</html>